all: clean fileopen fileread filewrite count

fileopen:
	gcc -Wall -o fileopen fileopen.c

fileread:
	gcc -Wall -o fileread fileread.c

filewrite:
	gcc -Wall -o filewrite filewrite.c

count:
	gcc -Wall -o count_marks count_marks.c

clean:
	-rm fileopen fileread filewrite count_marks
